### ISSUE TITLE
can not init turboAuthClient with @ardrive/turbo-sdk/web

### ISSUE THREAD

**Issue by EurekaChen** [ardriveapp/turbo-sdk#199]
**Describe the bug**
can not init TurboAuthClient in svelte.
error:
Uncaught (in promise) TypeError: import_arweave.default.init is not a function

**To Reproduce**
code:
```
<script lang="ts">	
	import {TurboFactory,developmentTurboConfiguration} from '@ardrive/turbo-sdk/web';
	import Arweave from 'arweave/web';

	async function publish(){		
		console.log("begin");
		const arweave = new Arweave({});
		const jwk = await arweave.wallets.generate();				
		const turboAuthClient = TurboFactory.authenticated({privateKey:jwk,...developmentTurboConfiguration});		
	}		
</script>
<h1>Error</h1>
<button onclick={publish}>publish</button>
```
click publish and get error:
```
@ardrive_turbo-sdk_web.js:283175 
 Uncaught (in promise) TypeError: import_arweave.default.init is not a function
    at new ArweaveToken (@ardrive_turbo-sdk_web.js:283175:54)
    at Object.arweave (@ardrive_turbo-sdk_web.js:319333:24)
    at _TurboFactory.getAuthenticatedTurbo (@ardrive_turbo-sdk_web.js:319844:81)
    at _TurboFactory.authenticated (@ardrive_turbo-sdk_web.js:320116:32)
    at HTMLButtonElement.publish (+page.svelte:9:40)
```

**Comment by dtfiedler** [comment]
Hi @EurekaChen, thanks for the bug report. Can you share your `package.json` as well as any gist or repos that can help us understand your project setup? That'll help us understand what could be causing the issue. Appreciate your patience!

**Comment by EurekaChen** [comment]
ok, thank you!
[package.json](https://github.com/user-attachments/files/17612975/package.json)
I have back sdk from 1.92.2 to 1.6.1, still have error.

**Comment by EurekaChen** [comment]
help

**Comment by dtfiedler** [comment]
@EurekaChen - can you try recently released v1.20.0?

**Comment by dtfiedler** [comment]
@EurekaChen - has your issue been resolved with the more recent releases?
