### ISSUE TITLE
BUG: ArconnectSigner byteLength check interfering with uploads in browser environment

### ISSUE THREAD

**Issue by Bobinstein** [ardriveapp/turbo-sdk#82]
**Describe the bug**
When instantiating Turbo in a browser environment by using ArconnectSigner from arbundles, a byteLength check is preventing turbo.uploadFile() to complete correctly. 

**To Reproduce**

1. Get permissions from Arconnect: `await window.arweaveWallet.connect(["ACCESS_PUBLIC_KEY", "SIGNATURE", 'ACCESS_ADDRESS', 'SIGN_TRANSACTION']);`
2. Instantiate ArconnectSigner: `const arConnectSigner = new ArconnectSigner(window.arweaveWallet);`
3. Instantiate Turbo: `const TurboInstance = await TurboFactory.authenticated({ signer: arConnectSigner });`
4. Obtain file via input element: 
```
const handleFileChange = (event) => {
    setSelectedFile(event.target.files[0]);
  };
```
5. Attempt to upload with Turbo:
```
const uploadResult = await turbo
      .uploadFile({
        fileStreamFactory: () => selectedFile.stream(),
        fileSizeFactory: () => selectedFile.size,
      })
```

**Expected behavior**
File should be uploaded to Arweave using Turbo, with ArconnectSigner signing the transaction from the ArConnect connected wallet

**Environment (please complete the following information):**

- Environment: nextjs, browser environment
- SDK Version: 1.4.1
- Node Version: 20.9.0
- Browser: Chrome

**Additional context**
Full code for page causing issue:

```
"use client";

import React, { useState, useEffect } from "react";

import { ArconnectSigner } from "arbundles/web";
import { TurboFactory } from "@ardrive/turbo-sdk/web";

import { USD } from "@ardrive/turbo-sdk/web";


export default function Home() {
  const [address, setAddress] = useState(null);
  const [signer, setSigner] = useState(null);
  const [turbo, setTurbo] = useState(null);
  const [selectedFile, setSelectedFile] = useState(null);


  useEffect(() => {
    console.log('Address updated:', address);
}, [address]);



  //function to generate checkout url
  const getURL = async () => {

    if(turbo && address){
      const {url} = await turbo.createCheckoutSession({
        amount: USD(80),
        owner: address
      })
      console.log(url)
      return url
    }
  }
  

  // sets state when file is uploaded
  const handleFileChange = (event) => {
    setSelectedFile(event.target.files[0]);
  };

  const handleFileUpload = async () => {
    if (!selectedFile || !turbo) return;
  

    const dataItemOpts = {tags: [{name: "test", value: "tag"}]} 
    try {
      console.log("Uploading file:", selectedFile.name);
  
      // const fileStreamFactory = () => selectedFile.stream();
      // const fileSizeFactory = () => selectedFile.size;

      const uploadResult = await turbo
      .uploadFile({
        fileStreamFactory: () => selectedFile.stream(),
        fileSizeFactory: () => selectedFile.size,
        dataItemOpts
      })
  
      console.log(uploadResult);
    } catch (error) {
      console.error("Error uploading file:", error);
    }
  };
  
  
  

  const handleConnectClick = async () => {
    await window.arweaveWallet.connect(["ACCESS_PUBLIC_KEY", "SIGNATURE", 'ACCESS_ADDRESS', 'SIGN_TRANSACTION']);
    const walletAddress = await window.arweaveWallet.getActiveAddress();
    setAddress(walletAddress);

    if (walletAddress) {
      const arConnectSigner = new ArconnectSigner(window.arweaveWallet);
      setSigner(arConnectSigner);

      const TurboInstance = await TurboFactory.authenticated({ signer: arConnectSigner });
      setTurbo(TurboInstance);
    }
  };

  return (
    <div>
      <main>
        <h1>Welcome to Your Next.js App</h1>
        <button onClick={handleConnectClick}>Connect to ArConnect</button>
        {address && <p>Connected to ArConnect - Address: {address}</p>}
        {signer && <p>ArConnect Signer Initialized</p>}
        {turbo && <p>Turbo Initialized</p>}
        {turbo && <button onClick={getURL}>Get checkout URL</button>}

        {/* File Upload Section */}
        {turbo && (
          <div>
            <input type="file" onChange={handleFileChange} />
            {selectedFile && (
              <button onClick={handleFileUpload}>Upload File</button>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
```

**Comment by Bobinstein** [comment]
**Error Message**

```
app-index.js:32 Error uploading file: TypeError: Cannot read properties of undefined (reading 'byteLength')
    at createData (web.bundle.min.js:130299:1)
    at TurboWebArweaveSigner.signDataItem (web.bundle.min.js:133650:1)
    at async TurboAuthenticatedUploadService.uploadFile (web.bundle.min.js:133384:58)
    at async handleFileUpload (page.js:56:28)
window.console.error @ app-index.js:32
handleFileUpload @ page.js:65
await in handleFileUpload (async)
callCallback @ react-dom.development.js:20461
invokeGuardedCallbackImpl @ react-dom.development.js:20510
invokeGuardedCallback @ react-dom.development.js:20585
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:20599
executeDispatch @ react-dom.development.js:31936
processDispatchQueueItemsInOrder @ react-dom.development.js:31968
processDispatchQueue @ react-dom.development.js:31981
dispatchEventsForPlugins @ react-dom.development.js:31992
eval @ react-dom.development.js:32182
batchedUpdates$1 @ react-dom.development.js:24793
batchedUpdates @ react-dom.development.js:28653
dispatchEventForPluginEventSystem @ react-dom.development.js:32181
dispatchEvent @ react-dom.development.js:29949
dispatchDiscreteEvent @ react-dom.development.js:29920
```

**Comment by dtfiedler** [comment]
Thanks for the report! This may have been fixed in https://github.com/ardriveapp/turbo-sdk/pull/86 and released in https://github.com/ardriveapp/turbo-sdk/releases/tag/v1.4.2 - can you confirm?

**Comment by Bobinstein** [comment]
All issues appear to have been resolved. Thank you
